apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: complex
  name: database-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
